version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/deploy:2022.09.1
    steps:
      - checkout
      - run:
          name: install python3-argcomplete dependency 
          command: |
            sudo apt update
            sudo apt install python3-argcomplete
      - run:
          name: install collection
          command: ansible-galaxy collection install community.general
      - run:
          name: list dirs
          command: |
            pwd
            ls -R
          working_directory: ~/.ansible/collections/ansible_collections/community/general
      - run:
          name: run integration list available targets
          command: ansible-test integration --list-targets
          working_directory: ~/.ansible/collections/ansible_collections/community/general
      - run:
          name: run integration filesize test
          command: ansible-test integration filesize --docker default
          working_directory: ~/.ansible/collections/ansible_collections/community/general
      - run:
          name: run integration filesize verbose test
          command: ansible-test integration filesize -vvv
          working_directory: ~/.ansible/collections/ansible_collections/community/general

