version: 2.1

workflows:
  build-and-unittest:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/deploy:2022.09.1
    steps:
      - checkout
      - run:
          name: install python3-argcomplete dependency 
          command: |
            sudo apt update
            sudo apt install python3-argcomplete
      - run:
          name: run integration ping test
          command: ansible-test integration ping
      - run:
          name: run integration lininfile test
          command: ansible-test integration lineinfile -vvv
      - run:
          name: run integration list available targets
          command: ansible-test integration --list-targets
